/**
 * MCP Skill Registry
 *
 * Handles operation requests from container skill MCP servers.
 * Containers write a skill_request IPC file; the host reads it here,
 * looks up the registered handler, runs it with stored credentials,
 * and writes the response back to ipc/{group}/responses/{reqId}.json.
 *
 * To add a new skill handler, import this module and call registerSkillHandler().
 * The /create-skill skill generates handler files that do exactly this.
 *
 * Security: credentials never leave the host process. The container only
 * ever receives operation results.
 */

import fs from 'fs';
import path from 'path';

import { resolveGroupIpcPath } from './group-folder.js';
import { logger } from './logger.js';
import { getSkillCredentials } from './db.js';

export interface SkillOperationContext {
  groupFolder: string;
  credentials: Record<string, string>;
}

export type SkillHandler = (
  params: Record<string, unknown>,
  ctx: SkillOperationContext,
) => Promise<unknown>;

const handlers: Map<string, SkillHandler> = new Map();

/**
 * Register a handler for a skill operation.
 * Key format: "{skillName}.{operationName}" (e.g., "email.send")
 *
 * Called by skill handler modules (generated by /create-skill).
 */
export function registerSkillHandler(
  skillName: string,
  operationName: string,
  handler: SkillHandler,
): void {
  const key = `${skillName}.${operationName}`;
  handlers.set(key, handler);
  logger.debug(
    { skill: skillName, operation: operationName },
    'Skill handler registered',
  );
}

/**
 * Process a skill_request IPC message from a container.
 * Writes the result (or error) to ipc/{groupFolder}/responses/{requestId}.json.
 */
export async function processSkillRequest(
  groupFolder: string,
  skillName: string,
  operation: string,
  params: Record<string, unknown>,
  requestId: string,
): Promise<void> {
  const key = `${skillName}.${operation}`;
  const handler = handlers.get(key);

  const responsesDir = path.join(resolveGroupIpcPath(groupFolder), 'responses');
  fs.mkdirSync(responsesDir, { recursive: true });
  const responsePath = path.join(responsesDir, `${requestId}.json`);

  if (!handler) {
    logger.warn(
      { groupFolder, skillName, operation, key },
      'No handler registered for skill operation',
    );
    const response = {
      success: false,
      error: `No handler registered for ${key}. Has the skill been fully set up? Run /create-skill to configure it.`,
    };
    fs.writeFileSync(responsePath, JSON.stringify(response, null, 2));
    return;
  }

  try {
    const credentials = getSkillCredentials(groupFolder, skillName);
    const ctx: SkillOperationContext = { groupFolder, credentials };
    const result = await handler(params, ctx);
    const response = { success: true, result };
    fs.writeFileSync(responsePath, JSON.stringify(response, null, 2));
    logger.info(
      { groupFolder, skillName, operation },
      'Skill request processed',
    );
  } catch (err) {
    const errorMsg = err instanceof Error ? err.message : String(err);
    logger.error(
      { groupFolder, skillName, operation, err },
      'Skill handler error',
    );
    const response = { success: false, error: errorMsg };
    fs.writeFileSync(responsePath, JSON.stringify(response, null, 2));
  }
}

/**
 * Auto-load skill handlers from src/skill-handlers/*.ts (compiled to .js).
 * Called at startup. Each handler file calls registerSkillHandler() on import.
 */
export async function loadSkillHandlers(handlersDir: string): Promise<void> {
  if (!fs.existsSync(handlersDir)) {
    logger.debug({ handlersDir }, 'No skill-handlers directory, skipping');
    return;
  }

  const files = fs.readdirSync(handlersDir).filter((f) => f.endsWith('.js'));
  for (const file of files) {
    const filePath = path.join(handlersDir, file);
    try {
      await import(filePath);
      logger.info({ file }, 'Loaded skill handler module');
    } catch (err) {
      logger.error({ file, err }, 'Failed to load skill handler module');
    }
  }
}
